Repository binary-hideout/elecritic, pull requests merged in 2020-12, with the labels that each got.

#49 Changed product category to a badge pill [PROPOSAL]
  Elecritic/Pages/ProductPage.razor
Labels: enhancement, frontend

#54 Database context for Index page
  Elecritic/Database/IndexContext.cs
  Elecritic/Pages/Index.razor
  Elecritic/Pages/Index.razor.cs
  Elecritic/Startup.cs
Labels: backend, database, enhancement

#53 Feature/avg rating card
  Elecritic/Pages/CategoriesCategory.razor
  Elecritic/wwwroot/vectors/star-fill.svg
Labels: enhancement, frontend

#56 Reviews include users
  Elecritic/Database/ProductContext.cs
  Elecritic/Pages/ProductPage.razor
  Elecritic/Pages/ProductPage.razor.cs
Labels: backend, database

#57 Feature/favorites context
  Elecritic/Database/MyFavoritesContext.cs
  Elecritic/Pages/Login.razor.cs
  Elecritic/Pages/MyFavorites.razor
  Elecritic/Pages/MyFavorites.razor.cs
  Elecritic/Shared/MainLayout.razor
  Elecritic/Shared/MainLayout.razor.cs
  Elecritic/Shared/NavMenu.razor
  Elecritic/Shared/NavMenu.razor.cs
  Elecritic/Startup.cs
Labels: enhancement

#58 Feature/review user
  Elecritic/Pages/ProductPage.razor
  Elecritic/wwwroot/vectors/person.svg
Labels: enhancement, frontend, proposal

#59 Feature/product card
  Elecritic/Components/ProductCard.razor
  Elecritic/Elecritic.csproj
  Elecritic/Pages/CategoriesCategory.razor
  Elecritic/Pages/Index.razor
  Elecritic/Pages/Index.razor.cs
  Elecritic/Pages/MyFavorites.razor
  Elecritic/_Imports.razor
Labels: enhancement, frontend

#61 Bugfix: Adding favorites and publishing reviews
  Elecritic/Database/ProductContext.cs
Labels: backend, bug, database

#60 Feature/log out
  Elecritic/Pages/Login.razor
  Elecritic/Pages/Logout.razor
  Elecritic/Pages/Logout.razor.cs
  Elecritic/Pages/Signup.razor
  Elecritic/Services/UserService.cs
  Elecritic/Shared/MainLayout.razor.cs
  Elecritic/Shared/NavMenu.razor
  Elecritic/Shared/NavMenu.razor.cs
Labels: backend, frontend

#62 Feature/recommendation system
  Elecritic/Helpers/FuzzyLogic.cs
  Elecritic/Services/ProductService.cs
Labels: backend, enhancement

#63 Recommendations system is complete
  Elecritic/Database/IndexContext.cs
  Elecritic/Database/MyFavoritesContext.cs
  Elecritic/Helpers/FuzzyLogic.cs
  Elecritic/Pages/Index.razor.cs
Labels: backend, database, enhancement

#64 Unit tests for UserService class
  Elecritic.UnitTests/Elecritic.UnitTests.csproj
  Elecritic.UnitTests/UserServiceTests.cs
Labels: backend

#65 Unit tests for Product model class
  Elecritic.UnitTests/ProductTests.cs
Labels: backend

#66 Unit tests for NavMenu component
  Elecritic.UnitTests/CategoryTests.cs
  Elecritic.UnitTests/CompanyTests.cs
  Elecritic.UnitTests/Fakes/FakeNavigationManager.cs
  Elecritic.UnitTests/NavMenuTests.cs
  Elecritic.UnitTests/ProductTests.cs
  Elecritic.UnitTests/UserServiceTests.cs
  Elecritic/Shared/MainLayout.razor
  Elecritic/Shared/MainLayout.razor.cs
  Elecritic/Shared/NavMenu.razor
  Elecritic/Shared/NavMenu.razor.cs
Labels: backend

#67 Validations on links and accesses of pages
  Elecritic/Database/CategoryProductsContext.cs
  Elecritic/Database/ProductContext.cs
  Elecritic/Database/UploadDataContext.cs
  Elecritic/Elecritic.csproj
  Elecritic/Pages/Categories.razor
  Elecritic/Pages/CategoriesCategory.razor
  Elecritic/Pages/CategoriesCategory.razor.cs
  Elecritic/Pages/MyFavorites.razor
  Elecritic/Pages/MyFavorites.razor.cs
  Elecritic/Pages/ProductPage.razor
  Elecritic/Pages/ProductPage.razor.cs
  Elecritic/Pages/UploadData.razor
  Elecritic/Pages/UploadData.razor.cs
  Elecritic/Pages/UploadFiles.razor
  Elecritic/Shared/NavMenu.razor
  Elecritic/Startup.cs
Labels: backend, frontend
