Repository binary-hideout/elecritic, pull requests merged in 2020-11, with the labels that each got.

#14 MainLayout and NavMenu.razor changed to fit current design ideas
  Elecritic/Shared/MainLayout.razor
  Elecritic/Shared/NavMenu.razor
  Elecritic/wwwroot/css/site.css
Labels: frontend

#18 Feature/review_model
  Elecritic/Models/Review.cs
Labels: backend, enhancement

#20 Feature/cards inicio
  Elecritic/Models/ProductService.cs
  Elecritic/Pages/Categorias.razor
  Elecritic/Pages/Index.razor
  Elecritic/Shared/NavMenu.razor
  Elecritic/wwwroot/carousel-images/alienware.jpg
  Elecritic/wwwroot/carousel-images/laptop_hp.png
  Elecritic/wwwroot/carousel-images/lenovo.jpg
  Elecritic/wwwroot/carousel-images/xiaomi.jpg
Labels: frontend

#19 Modify review model class
  Elecritic/Models/Review.cs
Labels: backend, enhancement

#23 Improvements on the ProductPage.razor view :)
  Elecritic/Pages/ProductPage.razor
Labels: frontend

#25 Services classes are now in a dedicated folder
  Elecritic/Models/WeatherForecast.cs
  Elecritic/Models/WeatherForecastService.cs
  Elecritic/Pages/Categories_cellphones.razor.cs
  Elecritic/Pages/FetchData.razor
  Elecritic/Pages/FetchData.razor.cs
  Elecritic/Pages/Index.razor.cs
  Elecritic/Pages/ProductPage.razor.cs
  Elecritic/Services/ProductService.cs
  Elecritic/Services/ReviewService.cs
  Elecritic/Startup.cs
Labels: enhancement

#26 Refactorization of model classes
  Elecritic.UnitTests/CategoryTests.cs
  Elecritic.UnitTests/CompanyTests.cs
  Elecritic.UnitTests/WeatherForecastTests.cs
  Elecritic/Models/Category.cs
  Elecritic/Models/Company.cs
  Elecritic/Models/Opinion.cs
  Elecritic/Models/Product.cs
  Elecritic/Models/Review.cs
  Elecritic/Models/User.cs
  Elecritic/Models/WeatherForecast.cs
  Elecritic/Services/ProductService.cs
  Elecritic/Services/ReviewService.cs
Labels: backend, enhancement

#28 One-to-many relationship for Category and Company
  Elecritic/Models/Category.cs
  Elecritic/Models/Company.cs
Labels: backend, enhancement

#30 Base database context class
  .gitignore
  Elecritic/Database/MainDbContext.cs
  Elecritic/Elecritic.csproj
  Elecritic/Models/Favorite.cs
  Elecritic/Models/Opinion.cs
  Elecritic/Models/User.cs
  Elecritic/Startup.cs
Labels: backend, database, enhancement

#24 feat<Login,Register,Host,CSS,imports> add the login and register interface...
  Elecritic/Elecritic.csproj
  Elecritic/Pages/Login.razor
  Elecritic/Pages/Login.razor.cs
  Elecritic/Pages/Register.razor
  Elecritic/Pages/Register.razor.cs
  Elecritic/Pages/_Host.cshtml
  Elecritic/_Imports.razor
  Elecritic/wwwroot/css/site.css
Labels: enhancement

#31 Passwords hasher
  Elecritic/Helpers/Hasher.cs
Labels: backend, enhancement

#36 Feature/model summary [Proposal]
  Elecritic/Models/Category.cs
  Elecritic/Models/Company.cs
  Elecritic/Models/Favorite.cs
  Elecritic/Models/Opinion.cs
  Elecritic/Models/Product.cs
  Elecritic/Models/Review.cs
  Elecritic/Models/User.cs
Labels: enhancement

#38 Database context for CategoriesCategory interface
  Elecritic/Database/CategoryProductsContext.cs
  Elecritic/Pages/Categories.razor
  Elecritic/Pages/CategoriesCategory.razor
  Elecritic/Pages/CategoriesCategory.razor.cs
  Elecritic/Startup.cs
Labels: backend, frontend

#41 Login and signup functionality with database
  Elecritic/Database/MainDbContext.cs
  Elecritic/Database/UserContext.cs
  Elecritic/Pages/Login.razor
  Elecritic/Pages/Login.razor.cs
  Elecritic/Pages/Signup.razor
  Elecritic/Pages/Signup.razor.cs
  Elecritic/Services/UserService.cs
  Elecritic/Startup.cs
Labels: backend, database

#45 Database functionality for ProductPage
  Elecritic/Database/ProductContext.cs
  Elecritic/Models/Product.cs
  Elecritic/Pages/ProductPage.razor
  Elecritic/Pages/ProductPage.razor.cs
  Elecritic/Startup.cs
Labels: backend, database, enhancement

#47 Feature/secciones favs
  Elecritic/Pages/Favoritos.razor
  Elecritic/Pages/Index.razor
  Elecritic/Pages/MyFavorites.razor
  Elecritic/Pages/MyFavorites.razor.cs
  Elecritic/Shared/MainLayout.razor
  Elecritic/Shared/NavMenu.razor
  Elecritic/wwwroot/css/site.css
Labels: enhancement

#48 Functionality to mark a product as favorite
  Elecritic/Database/ProductContext.cs
  Elecritic/Pages/ProductPage.razor
  Elecritic/Pages/ProductPage.razor.cs
Labels: backend, database

#50 Modify review's publish date [PROPOSAL]
  Elecritic/Pages/ProductPage.razor
Labels: enhancement, frontend

#52 Refactored method to get average rating of a review
  Elecritic/Database/CategoryProductsContext.cs
  Elecritic/Database/ProductContext.cs
  Elecritic/Pages/ProductPage.razor.cs
Labels: backend, enhancement
