Repository binary-hideout/elecritic, pull requests merged in 2023-05, with the labels that each got.

#51 Feature/dev team [PROPOSAL]
  Elecritic/Pages/Contributors.razor
  Elecritic/wwwroot/image/profile/brana.jpg
  Elecritic/wwwroot/image/profile/country.jpg
  Elecritic/wwwroot/image/profile/danyboy.jpg
  Elecritic/wwwroot/image/profile/milton.jpg
  Elecritic/wwwroot/image/profile/neto.jpg
  Elecritic/wwwroot/image/profile/ricky.png
  Elecritic/wwwroot/image/profile/robbie.png
  Elecritic/wwwroot/vectors/mark-github.svg
Labels: enhancement, proposal, frontend

#77 Update README
  README.md
  img/categories.png
  img/homepage.png
  img/product.png
Labels: documentation

#78 Merge last updates
  Elecritic/Pages/Contributors.razor
  Elecritic/wwwroot/image/profile/brana.jpg
  Elecritic/wwwroot/image/profile/country.jpg
  Elecritic/wwwroot/image/profile/danyboy.jpg
  Elecritic/wwwroot/image/profile/milton.jpg
  Elecritic/wwwroot/image/profile/neto.jpg
  Elecritic/wwwroot/image/profile/ricky.png
  Elecritic/wwwroot/image/profile/robbie.png
  Elecritic/wwwroot/vectors/mark-github.svg
  README.md
  img/categories.png
  img/homepage.png
  img/product.png
Labels: documentation, enhancement
